services:
    db:
      image: postgres:17
      container_name: django-todo-db
      environment:
        POSTGRES_DB: ${DB_NAME}
        POSTGRES_USER: ${DB_USER}
        POSTGRES_PASSWORD: ${DB_PASSWORD}
      ports:
        - "5432:5432"
      volumes:
        - postgres_data:/var/lib/postgresql/data
      env_file:
        - .env
    
    django-web:
      build: .
      container_name: django-todo-app
      ports:
        - "8000:8000"
      depends_on:
        - db
      environment:
        DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
        DJANGO_DEBUG: ${DJANGO_DEBUG}
        DJANGO_LOGLEVEL: ${DJANGO_LOGLEVEL}
        DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}
        DJANGO_DATABASE_ENGINE: ${DJANGO_DATABASE_ENGINE}
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASSWORD: ${DB_PASSWORD}
        DB_URL: ${DB_URL}
        DB_PORT: ${DB_PORT}
      env_file:
        - .env
        
volumes:
  postgres_data: