services:
    django-web:
      build: .
      container_name: django-todo-app
      ports:
        - "8000:8000"
      environment:
        DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
        DJANGO_DEBUG: ${DJANGO_DEBUG}
        DJANGO_LOGLEVEL: ${DJANGO_LOGLEVEL}
        DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}
        DJANGO_DATABASE_ENGINE: ${DJANGO_DATABASE_ENGINE}
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASSWORD: ${DB_PASSWORD}
        DB_URL: ${DB_URL}
        DB_PORT: ${DB_PORT}
      env_file:
        - .env