# Generated by Django 5.1.7 on 2025-07-10 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
